package quadlet

import (
	"regexp"
	"strings"
)

// Generated is a unit generated by quadlet, as the dry run prints it.
type Generated struct {
	Name     string   `json:"name"`
	Source   string   `json:"source,omitempty"`
	Requires []string `json:"requires,omitempty"`
	After    []string `json:"after,omitempty"`
	// Volumes and Networks are the sources of -v/--volume/--mount and the --network values of
	// podman run: what the container really uses.
	Volumes  []string `json:"volumes,omitempty"`
	Networks []string `json:"networks,omitempty"`
	// Creates is the volume or network created by a .volume/.network unit.
	Creates string `json:"creates,omitempty"`
}

var blockHeader = regexp.MustCompile(`^---(.+)---$`)

// parseDryRun parses the units printed by quadlet -dryrun: "---name.service---" followed by the
// unit content.
func parseDryRun(lines []string) map[string]*Generated {
	out := map[string]*Generated{}
	var cur *Generated
	var body []string
	flush := func() {
		if cur == nil {
			return
		}
		u := ParseUnit(body)
		cur.Source = u.Value("Unit", "SourcePath")
		cur.Requires = splitUnits(u.Values("Unit", "Requires"))
		cur.After = splitUnits(u.Values("Unit", "After"))
		if exec := u.Value("Service", "ExecStart"); exec != "" {
			parseExecStart(exec, cur)
		}
		out[cur.Name] = cur
	}
	for _, l := range lines {
		if m := blockHeader.FindStringSubmatch(strings.TrimSpace(l)); m != nil {
			flush()
			cur, body = &Generated{Name: m[1]}, nil
			continue
		}
		body = append(body, l)
	}
	flush()
	return out
}

func splitUnits(values []string) []string {
	var out []string
	for _, v := range values {
		out = append(out, strings.Fields(v)...)
	}
	return out
}

// parseExecStart extracts from the podman command line the volumes and networks it uses, or the
// volume/network it creates.
func parseExecStart(exec string, g *Generated) {
	args := strings.Fields(exec)
	if len(args) < 2 {
		return
	}
	sub := ""
	for _, a := range args[1:] {
		if !strings.HasPrefix(a, "-") {
			sub = a
			break
		}
	}
	switch sub {
	case "volume", "network":
		// podman volume create --ignore [--opt ...] NAME
		g.Creates = args[len(args)-1]
		return
	}
	value := func(i int, a, long, short string) (string, bool) {
		switch {
		case a == long || (short != "" && a == short):
			if i+1 < len(args) {
				return args[i+1], true
			}
		case strings.HasPrefix(a, long+"="):
			return strings.TrimPrefix(a, long+"="), true
		}
		return "", false
	}
	for i, a := range args {
		if v, ok := value(i, a, "--volume", "-v"); ok {
			src, _, _ := strings.Cut(v, ":")
			g.Volumes = append(g.Volumes, src)
		}
		if v, ok := value(i, a, "--mount", ""); ok {
			for _, opt := range strings.Split(v, ",") {
				if k, val, ok := strings.Cut(opt, "="); ok && (k == "source" || k == "src") {
					g.Volumes = append(g.Volumes, val)
				}
			}
		}
		if v, ok := value(i, a, "--network", ""); ok {
			g.Networks = append(g.Networks, v)
		}
	}
}

var converting = regexp.MustCompile(`converting "([^"]+)": (.*)$`)

// parseDiagnostics splits the quadlet messages by source file; the others are general.
func parseDiagnostics(stderr string) (byFile map[string][]string, general []string) {
	byFile = map[string][]string{}
	for _, l := range strings.Split(stderr, "\n") {
		l = strings.TrimSpace(l)
		if _, msg, ok := strings.Cut(l, "]: "); ok && strings.HasPrefix(l, "quadlet") {
			l = msg
		}
		if l == "" || strings.HasPrefix(l, "Loading source unit file") {
			continue
		}
		if m := converting.FindStringSubmatch(l); m != nil {
			byFile[m[1]] = append(byFile[m[1]], m[2])
			continue
		}
		general = append(general, l)
	}
	return byFile, general
}
