#!/usr/bin/env bash

set -e

TOOL_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$TOOL_SOURCE" ] ; do TOOL_SOURCE="$(readlink "$TOOL_SOURCE")"; done
SDLC_DIR="$( cd -P "$( dirname "$TOOL_SOURCE" )" && pwd )"
PRJ_HOME="$( cd -P "$( dirname "$SDLC_DIR" )" && pwd )"

source "${SDLC_DIR}/config"

BIN_DIR="${PRJ_HOME}/bin"
if [[ -d "$BIN_DIR" ]]; then rm -r "$BIN_DIR"; fi
mkdir "$BIN_DIR"

cd "${PRJ_HOME}"

ldflags="$(go_ldflags)"
echo "building ${REPO_NAME} ${APP_VERSION}"

for dir in $(find "${PRJ_HOME}/cmd" -mindepth 1 -maxdepth 1 -type d); do
  app_name=$(basename "$dir")
  echo "=== ${app_name}"
  go build "${GO_BUILD_FLAGS[@]}" -ldflags "$ldflags" -o "${BIN_DIR}/${app_name}" "${MODULE}/cmd/${app_name}"
done
