#!/usr/bin/env bash

set -e

TOOL_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$TOOL_SOURCE" ] ; do TOOL_SOURCE="$(readlink "$TOOL_SOURCE")"; done
SDLC_DIR="$( cd -P "$( dirname "$TOOL_SOURCE" )" && pwd )"
PRJ_HOME="$( cd -P "$( dirname "$SDLC_DIR" )" && pwd )"

BIN_DIR="${PRJ_HOME}/bin"
if [[ -d "$BIN_DIR" ]]; then rm -r "$BIN_DIR"; fi

BUILD_DIR="${PRJ_HOME}/build"
if [[ -d "$BUILD_DIR" ]]; then rm -r "$BUILD_DIR"; fi

DIST_DIR="${PRJ_HOME}/dist"
if [[ -d "$DIST_DIR" ]]; then rm -r "$DIST_DIR"; fi
